apiVersion: v1
kind: Service
metadata:
  name: currency-api-service
spec:
  selector:
    app: currency-api
  ports:
  - name: http
    port: 80
    targetPort: 5000
  type: LoadBalancer  # Pour accéder depuis l'extérieur